Sisaf\SisafBundle\Entity\Cuotas:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        Persona:
            type: string
            length: 255
        Tipo:
            type: string
            length: 255
        Descripcion:
            type: string
            length: 255
        Fecha:
            type: date
        Monto:
            type: decimal
        Frecuencia:
            type: string
            length: 225
    manyToOne:
        usuario:
            targetEntity: Usuario
            inversedBy: Cuotas
            joinColumn:
                name: usuario_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
