Sisaf\SisafBundle\Entity\Cuotas:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        Descripcion:
            type: string
            length: 255
        fechaDeInicio:
<<<<<<< HEAD
            type: datetime
            nullable: true
        fechaFinal:
            type: datetime
            nullable: true
        diasRecurrencia:
            type: integer
            nullable: true
        diaproximo:
            type: integer
=======
            type: date
            nullable: true
        fechaFinal:
            type: date
            nullable: true
        diasRecurrencia:
            type: string
            length: 40
            nullable: true
        diaproximo:
            type: date
>>>>>>> a8cfb7fd1de2239305c78222c67776e4b269bdb9
            nullable: true
        monto:
            type: decimal
        tipo:
            type: integer
<<<<<<< HEAD
=======
        padre:
            type: integer
            nullable: true
     
>>>>>>> a8cfb7fd1de2239305c78222c67776e4b269bdb9
    lifecycleCallbacks: {  }
