Sisaf\SisafBundle\Entity\Cuotas:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        Descripcion:
            type: string
            length: 255
        fechaDeInicio:
            type: date
            nullable: true
        fechaFinal:
            type: date
            nullable: true
        diasRecurrencia:
            type: string
            length: 40
            nullable: true
        diaproximo:
            type: date
            nullable: true
        monto:
            type: decimal
        tipo:
            type: integer
        padre:
            type: integer
            nullable: true
     
    lifecycleCallbacks: {  }
