Sisaf\SisafBundle\Entity\Morosos:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        Persona:
            type: string
            length: 255
        Correo:
            type: string
            length: 255
        Telefono:
            type: integer
        Recidencia:
            type: string
            length: 255
    lifecycleCallbacks: {  }
