Sisaf\SisafBundle\Entity\QuejSug:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        Titulo:
            type: string
            length: 255
        Descripcion:
            type: text
            length: 1000
        Fecha:
            type: date
        Hora:
            type: time
    lifecycleCallbacks: {  }
