Sisaf\SisafBundle\Entity\Usuario:
    type: entity
    table: null
    repositoryClass: Sisaf\SisafBundle\Entity\UsuarioRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: '25'
        password:
            type: string
            length: '64'
        email:
            type: string
            length: '60'
#        roles:
#            type: string
#            length: '25'
    lifecycleCallbacks: {  }
