Sisaf\SisafBundle\Entity\Usuario:
    type: entity
    table: null
    repositoryClass: Sisaf\SisafBundle\Entity\UsuarioRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: '25'
        password:
            type: string
            length: '64'
        email:
            type: string
            length: '60'
    manyToMany:
        roles:
            targetEntity: Sisaf\SisafBundle\Entity\role
            joinTable:
                name: user_role
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    role_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }
