parameters:
    database_driver:   pdo_pgsql
    database_host:     127.0.0.1
    database_port:     
    database_name:     mypgdatabase
    database_user:     mypguser
    database_password: dscorp2000

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt


#Default:witouth postgres
#    database_driver:   pdo_pgsql
#    database_host:     127.0.0.1
#    database_port:     ~
#    database_name:     sisaf
#    database_user:     root
#    database_password: dscorp2000