Sisaf_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SisafBundle:Default:index }

Sisaf_subir:
    pattern:  /Documentos
    defaults: { _controller: SisafBundle:Default:subir }

sisafBundle_inicio:
        resource: "@SisafBundle/Resources/config/routing/inicio.yml"
        prefix:   /Inicio

SisafBundle_clientes:
        resource: "@SisafBundle/Resources/config/routing/clientes.yml"
        prefix:   /Clientes

SisafBundle_Proveedores:
        resource: "@SisafBundle/Resources/config/routing/proveedores.yml"
        prefix:   /Proveedores

SisafBundle_visitantes:
        resource: "@SisafBundle/Resources/config/routing/visitantes.yml"
        prefix:   /Visitantes

SisafBundle_Avisos:
        resource: "@SisafBundle/Resources/config/routing/avisos.yml"
        prefix:   /Avisos

SisafBundle_egresos:
        resource: "@SisafBundle/Resources/config/routing/egresos.yml"
        prefix:   /Egresos

SisafBundle_ingresos:
        resource: "@SisafBundle/Resources/config/routing/ingresos.yml"
        prefix:   /Ingresos

SisafBundle_presupuesto:
        resource: "@SisafBundle/Resources/config/routing/presupuesto.yml"
        prefix:   /Presupuesto

SisafBundle_gastosfijos:
        resource: "@SisafBundle/Resources/config/routing/gastosfijos.yml"
        prefix:   /GastosFijos

SisafBundle_estadofinanciero:
        resource: "@SisafBundle/Resources/config/routing/estadofinanciero.yml"
        prefix:   /EdoFinanciero

SisafBundle_cuotas:
        resource: "@SisafBundle/Resources/config/routing/cuotas.yml"
        prefix:   /Cuotas

SisafBundle_quejsug:
        resource: "@SisafBundle/Resources/config/routing/quejsug.yml"
        prefix:   /Quejas_Sugerencias

SisafBundle_morosos:
        resource: "@SisafBundle/Resources/config/routing/morosos.yml"
        prefix:   /Morosos

SisafBundle_soporte:
        resource: "@SisafBundle/Resources/config/routing/soporte.yml"
        prefix:   /Soporte