regegresos:
    pattern:  /
    defaults: { _controller: "SisafBundle:RegEgresos:index" }

regegresos_show:
    pattern:  /{id}/show
    defaults: { _controller: "SisafBundle:RegEgresos:show" }

regegresos_new:
    pattern:  /new
    defaults: { _controller: "SisafBundle:RegEgresos:new" }

regegresos_create:
    pattern:  /create
    defaults: { _controller: "SisafBundle:RegEgresos:create" }
    requirements: { _method: post }

regegresos_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SisafBundle:RegEgresos:edit" }

regegresos_update:
    pattern:  /{id}/update
    defaults: { _controller: "SisafBundle:RegEgresos:update" }
    requirements: { _method: post }

regegresos_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SisafBundle:RegEgresos:delete" }
    requirements: { _method: post }
