usuario:
    pattern:  /
    defaults: { _controller: "SisafBundle:Usuario:index" }

usuario_show:
    pattern:  /{id}/show
    defaults: { _controller: "SisafBundle:Usuario:show" }

usuario_new:
    pattern:  /new
    defaults: { _controller: "SisafBundle:Usuario:new" }

usuario_create:
    pattern:  /create
    defaults: { _controller: "SisafBundle:Usuario:create" }
    requirements: { _method: post }

usuario_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "SisafBundle:Usuario:edit" }

usuario_update:
    pattern:  /{id}/update
    defaults: { _controller: "SisafBundle:Usuario:update" }
    requirements: { _method: post }

usuario_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "SisafBundle:Usuario:delete" }
    requirements: { _method: post }
usuario_piso:
    path:     /piso_ajax
    defaults: { _controller: "SisafBundle:Usuario:piso" }
    methods:  POST

usuario_departamento:
    path:     /departamento_ajax
    defaults: { _controller: "SisafBundle:Usuario:departamento" }
    methods:  POST

