<?php

namespace Trabajo\bdBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArchivosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchivosRepository extends EntityRepository
{
}
